dist: xenial
addons:
  apt:
    packages:
    - libgnutls28-dev
language: python
before_install: openssl version
env:
  global:
    - secure: AifoKzwhjV94cmcQZrdQmqRu/9rkZZvWpwBv1daeAQpLOKFPGsOm3D+x2cSw9+iCfkgDZDfqQVv1kCaFVxTll8v8jTq5SJdqEY0NmGWbj/UkNtShh609oRDsuzLxAEwtVKYjf/h8K2BRea+bl1tGkwZ2vtmYS6dxNlAijjWOfds=
    - secure: LBSEg/gMj4u4Hrpo3zs6Y/1mTpd2RtcN49mZIFgTdbJ9IhpiNPqcEt647Lz94F9Eses2x2WbNuKqZKZZReY7QLbEzU1m0nN5jlaKrjcG5NR5clNABfFFyhgc0jBikyS4abAG8jc2efeaTrFuQwdoF4sE8YiVrkiVj2X5Xoi6sBk=
  matrix:
    - DEPENDENCY="boto"
    - DEPENDENCY="aiohttp"
    - DEPENDENCY="others"
    - DEPENDENCY="flask"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - env: DEPENDENCY="boto"
    - python: "pypy3"
      env: DEPENDENCY="aiohttp"

install:
  - pip install tox-travis
script:
  - tox
